### ISSUE TITLE
Stupids

### ISSUE THREAD

**Issue by kangp3** [whereuat/whereuat-android#11]
- change package name to to "com.whereuat.whereuat". Or better yet, why not just "com.whereuat"? Do we have the technology? Either way, "com.whereuat.whereu" looks dirty.
- Change `mVerfiyCode` to `mVerificationEdit` in `LoginActivity`
- `public static final String ACCOUNT_NEW_BROADCAST = "com.whereuat.whereu.ACCOUNT_NEW_BROADCAST";` can be one line in `Constants`
- change Internet permission line to have a space before `/>`

**Comment by kangp3** [comment]
- Delete the unnecessary imports in WhereuatContract

**Comment by kangp3** [comment]
- Fix the spaces in the class definition of SquareAdapter

**Comment by JuliusAlexanderIV** [comment]
- in `MainActivity` we can use `this` instead of `this.getApplicationContext()` for creating the `ContactRetriever`

**Comment by JuliusAlexanderIV** [comment]
- Fix the stuff in `MainActivity` that goes over the line limit.

**Comment by kangp3** [comment]
- Change column names for the Entry classes (get rid of the middle `_NAME_`)

**Comment by kangp3** [comment]
- Add a default constructor for DbTask class

**Comment by kangp3** [comment]
- Add `PERMISSIONS_REQUEST_READ_CONTACTS` to `Constants`

**Comment by JuliusAlexanderIV** [comment]
- in `MainActivity` the params for `onActivityResult` should be snake-case
