### ISSUE TITLE
Build push notification for when atRespond comes in from server

### ISSUE THREAD

**Issue by kangp3** [whereuat/whereuat-android#76]

**Comment by JuliusAlexanderIV** [comment]
So how do you wanna determine what kind of push to display? We could add a flag to the notification data like `"notification-type"` and it could have the values `"AT_REQUEST"` and `"AT_RESPONSE"`.

We could also just do a check on what data is in the notification, ie. if we find only `"from-#"` and `"to-#"` it's an @request but if we also find `"current-location"` and `"key-location"` it's an @response.

**Comment by JuliusAlexanderIV** [comment]
We'll use a flag

**Comment by JuliusAlexanderIV** [comment]
Waiting for iOS to figure its stuff out before moving ahead with this.
